create procedure p_load_custom_lists(IN p_law_firm_id bigint)
begin
    -- @@formatter:off
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Academic Diplomas', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Affidavit Documents', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Applicant Statements', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Articles of Organization for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Asylum Claim', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Bankruptcy Documents', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Biometrics', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Birth Certificate', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Certificate of Shares for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Certification of Completion/ Attendance of English Language Courses', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Certificate from Vocational School ', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Citizenship Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Common Categories of documents we use:', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Company Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Company Pay Roll for the Foreign Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Company Pay Roll for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Bank Statements for the Foreign Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Bank Statements for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Business Plan for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Marketing Materials for the Foreign Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Marketing Materials for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Organizational Documents for the Foreign Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Corporate Tax Return for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Court Records', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Criminal History', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Derivative Beneficiary', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Divorce Certificate', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Documents Showing Continued Payment of Bills ', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Education', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Emotional/Psychological Effects', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Employment Certificate', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Evaluation Equivalency of Foreign Education/ Degrees', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Family Certificate', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Family Members', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Federal Employment Identification Number', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Financial Considerations', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Financials', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Foreign Tax Return', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Form 941', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Health Insurance Card With Effective and Expiration Dates', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','High School Diploma', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','I-130 Form', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','I-140 Form', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','I-918 Form', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','I-94 Form', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Identification Card', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Indication of Character', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Invoice for Foreign Company (Sales, Purchase, Utilities)', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Invoice for U.S. Company (Sales, Purchase, Utilities)', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','IRS Form 1095-B, Health Coverage', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','IRS Form 1095-C, Employer-Provided Health Insurance Offer and Coverage', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','IRS Form 8963, Report of Health Insurance Provider Information', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','IRS Form 8962, Premium Tax Credit', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Joint Sponser Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','L-1A Executive', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','L-1A Manager', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Loan Documents (auto, tuition, credit card, etc…)', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','L-1b Specialized Knowledge', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Marital Status', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Marriage Certificate', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Medical Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Medical Reasons', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Medical Records', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Mortgage Statement', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Naturalization', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Occupational License/ Certification', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Organizational Chart for the Foreign Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Organizational Chart for the U.S. Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Other Type', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Passport', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Passport-Type Photos', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Pay Stubs', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Personal Considerations', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Photos of Business Premises for the Foreign company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Previous I-797 Notices', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Bona Fide Marriage', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Company', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Company Funds', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Education', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Employer Compliance', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Investment', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Petitioner Citizenship', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Presence', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Relationship', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Residence', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Proof of Visa', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Public Benefits Receipt or Certification', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Public Benefits - Documents Showing Dis-enrollment/ Withdrawing ', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Qualifying Relationship', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Questionnaire', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Real Estate Appraisal Letter', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Reference Letters on Behalf of Beneficiary', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','References', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Resume/C.V.', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Social Security Numbr', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Source of Investment Funds', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Statements of Stocks and Bond Portfolio', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Supportive Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Translation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','U.S. Credit Report (from one of Equifax, Experian, or TransUnion)', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','USCIS Notice - Copy Showing the Fee was Waived', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','USC/LPR Documentation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','USCIS Notice', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Visa', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Waiver', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Wellness', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Witness Statements', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Witnesses', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'DOCUMENT_TYPE','Work Authorization', true);

    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CASE_VENUE','Court', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CASE_VENUE','USCIS', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CASE_VENUE','USCIS/Court', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CASE_VENUE','Other', true);

    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','42B', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Application for Relief', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Biometrics', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Brief', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','CAL-DOJ', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Consolidation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Conviction Documents', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Country Conditions / DOS Report', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Criminal History Chart', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Detailed Declarations & Cert Translation', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Diagnosis / Treatment / Prognosis', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Fee Receipt', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','I-130 / I-140', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','I-360 or I-751', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','I-589', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Other: ', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Passport & Translation of All Visas/Stamps', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Police Reports', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','PSG - Nexus & Cognizability Brief', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','REAL ID / Supplement Documents', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Travel History', true);
    insert into custom_list (law_firm_id, type, text, config_default) VALUES (p_law_firm_id, 'CALL_UP','Witness List & Declaration', true);

    insert into custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Advertisement',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Client Referral',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Facebook',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','LinkedIn',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Networking Event',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Professional Referral',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Search',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Twitter',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Website',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Yelp',1);
    INSERT INTO custom_list (law_firm_id,type, text,config_default) VALUES (p_law_firm_id,'REFERRAL_SOURCE','Other',1);

    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N/A' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','None' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','1B1 - H-1B1 SPECIALITY OCCUPATION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','1B2 - H-1B2 DoD SPECIALITY' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','1B3 - H-1B3 FASHION MODEL' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','1B4 - H-1B4 UNIQUE PGM ARTIST-ENT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','1B5 - H-1B5 ALIEN ATHLETE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','1BS - SUPPORT PERSON OF H-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','A1 - AMBASSADOR, DIPLOMAT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','A2 - OTHER DIPLOMATIC OFFICIALS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','A3 - ATTENDANTS OF A-1, A-2' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','AS - ASYLUM' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','ASD - ASYLUM STATUS DENIED' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','AW - RAW APPLIED FOR AT A PORT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','B1 - TEMPORARY VISITOR FOR BUSINESS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','B1A - NI PERSNL-DOM SRVANT OF NI EMP' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','B1B - NI DOMESTIC SERVANT OF USC' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','B1C - NI EMPLOYED BY FOREIGN AIRLINE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','B1D - NI - MISSIONARIES' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','B2 - TEMPORARY VISITOR FOR PLEASURE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','BE - BERING STRAIT ENTRIES' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','C1 - ALIEN IN TRANSIT THROUGH U.S.' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','C2 - ALIEN IN TRANSIT TO UN HQ' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','C3 - FRN GOV OFF IN TRANSIT THRU US' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','C4 - TRANSIT WITHOUT A VISA' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','CC - CUBAN MASS MIGRATION PROJECT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','CH - PAROLEE (HUMANITARIAN-HQ AUTH)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','CP - PAROLEE (PUBLIC INT-HQ AUTH)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','CW1 - PRINCIPAL TRANSITIONAL WORKERS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','CW2 - DEPENDENT OF CW1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','D1 - ALIEN CREW DEPART SAME VESSEL' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','D2 - ALIEN CREW DEPART OTHER VESSEL' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','DA - ADVANCE PAROLE (DISTRICT AUTH)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','DE - PAROLEE (DEFERRED INSPECTION)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','DT - PAROLEE (DISTRICT-POE AUTH)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','DX - CREW ARRIVING DETAINED ON SHIP' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','E1 - TREATY TRADER-SPOUSE-CHILDREN' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','E2 - TREATY INVESTOR-SPOUSE-CHILD' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','E2C - CNMI INVESTOR' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','E3 - AUSTRALIA FREE TRADE AGREEMENT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','EAO - EMPLOYMENT ADVISORY OPTION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','EWI - ENTRY WITHOUT INSPECTION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','X - EOIR' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','F1 - STUDENT - ACADEMIC' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','F2 - SPOUSE-CHILD OF F-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','FSM - CFA ADM FED STATES MICRONESIA' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','FUG - FAMILY UNITY GRANTED' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','G1 - PRINCIPAL REP. FOREIGN GOVT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','G2 - OTHER REP FOREIGN GOVT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','G3 - REP NON-RECOGNIZED FOREIGN GOV' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','G4 - OFFICER-EMPLOYEE INTL. ORG.' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','G5 - ATTENDANTS OF G1, G2, G3, G4' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','GB - VISITOR WITHOUT A VISA 15 DAYS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','GT - VISITOR WITHOUT A VISA 15 DAYS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H1 - ALIEN OF DIST MERIT & ABILITY' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H1A - REGISTERED NURSE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H1B - SPECIALITY OCCUPATION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H1C - NURSE RELIEF' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H2 - TEMPORARY LABOR CERTIFICATION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H2A - TEMPORARY AGRICULTURAL WORKER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H2B - TEMPORARY NON-AG WORKER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H2R - RET(H2B)WRKR NOT SUBJCT TO CAP' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H3 - ALIEN TRAINEE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H3A - TRAINEE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H3B - SPECIAL EDUCATION TRAINING' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','H4 - SPS OR CHLD OF H1,H2,H3 OR H2R' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','HSC - FREE TRADE H1B1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','I - FOREIGN PRESS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','IMM - IMMIGRANT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','IN - INDEFINITE PAROLE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','J1 - EXCHANGE VISITOR - OTHERS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','J1S - EXCHANGE VISITOR - STUDENT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','J2 - SPOUSE-CHILD OF J-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','J2S - SPOUSE-CHILD OF J-1S' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','K1 - ALIEN FIANCE(E) OF USC' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','K2 - CHILD OF K1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','K3 - SPOUSE OF USC' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','K4 - CHILD OF USC' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','L1 - INTRA-COMPANY TRANSFEREE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','L1A - MANAGER OR EXECUTIVE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','L1B - SPECIALIZED KNOWLEDGE ALIEN' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','L2 - SPOUSE-CHILD OF L-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','LZ - BLANKET L PETITION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','M1 - STUDENT - VOCATIONAL-NON-ACAD.' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','M2 - SPOUSE-CHILD OF M-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','MIS - CFA ADM REP MARSHALL ISLANDS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','ML - PAROLEE-MEDICAL, LEGAL, HUMAN' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N1 - PRINCIPAL REP. OF NATO MEMBER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N2 - OTHER REP. OF NATO MEMBER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N3 - CLERICAL STAFF FOR N-1, N-2' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N4 - OFFICIALS OF NATO' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N5 - EXPERTS EMPLOYED BY NATO' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N6 - CIVILIAN COMPONENT OF NATO' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N7 - ATTENDANTS OF N-1 THROUGH N-6' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N8 - PARENT OF SPEC IMMIGRANT CHILD' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','N9 - SPOUSE-CHILD OF N8' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','O1 - ALIEN W-EXTRAORDINARY ABILITY' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','O1A - EXTRAORDINARY ALIEN - NON-ARTS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','O1B - EXTRAORDINARY ALIEN IN ARTS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','O2 - ACCOMPANYING ALIEN TO O1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','O3 - SPOUSE-CHILD OF O-1, O-2' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','OP - PAROLEE (OVERSEAS AUTHORIZED)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P1 - ATHLETE OR ENTERTAINER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P1A - ALIEN WITH ATHLETIC EVENT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P1B - ALIEN WITH ENTERTAINMENT GROUP' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P1S - SUPPORT PERSON OF P-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P2 - EXHANGE ARTIST-ENTERTAINER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P2S - SUPPORT PERSON OF P-2' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P3 - UNIQUE PGM ARTIST-ENTERTAINER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P3S - SUPPORT PERSON OF P-3' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','P4 - SPOUSE-CHILD OF P-1, P-2, P-3' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','PAL - CFA ADMISSION PALAU' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','PAR - PAROLEE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','PI - PACIFIC ISLANDER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','Q1 - INTL CULTURAL XCHG VISITORS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','Q2 - IRISH PEACE PROCESS PARTICPNTS' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','Q3 - SPOUSE-CHILD OF Q2' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','R1 - RELIGIOUS OCCUPATION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','R2 - SPOUSE-CHILD OF R-1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','RE - REFUGEE' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','RE5 - HAITIAN W-GRANTED REFUGEE STAT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','RW - RAW APPLIED FOR AT A US CO' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','S1 - SPECIAL AGRICULTURAL WORKER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','S2 - SPECIAL AGRICULTURAL WORKER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','S9 - EMERGENCY FARM WORKER' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','SDF - SUSPECTED DOCUMENT FRAUD' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','ST - STOWAWAY' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','T1 - VICTIM OF SEVERE FORM OF TRAFK' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','T2 - SPOUSE OF T1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','T3 - CHILD OF T1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','T4 - PARENT OF T1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','T5 - UNMARRIED UNDER 18 SIBLG T1 NI' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','TB - SPOUSE OR CHILD OF CAN. FR' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','TC - CANADIAN FREE TRADE AGREEMENT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','TD - NAFTA DEPENDENT' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','TN1 - NAFTA PRINCIPAL (CANADA)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','TN2 - NAFTA PRINCIPAL (MEXICO)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','TWO - TRANSIT WITHOUT A VISA' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','U1 - VICTIM OF CRIMINAL ACTIVITY' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','U2 - SPOUSE OF U1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','U3 - CHILD OF U1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','U4 - PARENT OF U1' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','U5 - UNMARRIED UNDER 18 SIBLG U1 NI' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','UN - UNKNOWN' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','UU - UNKNOWN' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','V1 - SPOUSE OF LPR' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','V2 - CHILD OF LPR' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','V3 - CHILD OF V2' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','WB - VISITOR FOR BUSINESS - VWPP' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','WD - WITHDRAWL (I-p_law_firm_id)' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','WI - WITHOUT INSPECTION' , 0, p_law_firm_id);
    INSERT INTO custom_list (type, text, config_default, law_firm_id) VALUES ('CURRENT_STATUS','WT - VISITOR FOR PLEASURE - VWPP' , 0, p_law_firm_id);


    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Start', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Gather or Collect', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Preparation', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('File', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Processing', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Review', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Decision', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Complete', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Appeal', p_law_firm_id);
    INSERT INTO milestone_config (name, law_firm_id) VALUES ('Court', p_law_firm_id);

-- @@formatter:on
end;

